apiVersion: v1
kind: Secret
metadata:
  name: line-notify-secret
  namespace: line-notify
type: Opaque
data:
  CLIENT_ID: ''
  CLIENT_SECRET: ''


## Deployment
#spec:
#  template:
#    spec:
#      containers:
#        - name: line-notify-git
#          image: >-
#            image-registry.openshift-image-registry.svc:5000/line-notify/line-notify-git@sha256:3ac939dab9ca76431bacf6acaacd69bc6f5b9b8e6a2966bc55dc49a61b66f9b9
#          ports:
#            - containerPort: 8080
#              protocol: TCP
#          env:
#            - name: CLIENT_ID
#              valueFrom:
#                secretKeyRef:
#                  name: line-notify-secret
#                  key: CLIENT_ID
#            - name: CLIENT_SECRET
#              valueFrom:
#                secretKeyRef:
#                  name: line-notify-secret
#                  key: CLIENT_SECRET